# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=nirvana
mod_name=Nirvana
mod_author=possible_triangle
mod_version=0.0.0-dev
release_type=release

# Common
mc_version=26.1.2
parchment_mappings_version=2024.11.17

# Forge
neoforge_version=21.1.219

# Fabric
fabric_api_version=0.149.1+26.1.2
fabric_loader_version=0.19.2

# Publishing
repository=teamgalena/nirvana
maven_group=dev.galena
curseforge_project_id=1278909
modrinth_project_id=7vLeZs9H
